### ISSUE TITLE
Why the image size is 26cmX26cm?

### ISSUE THREAD

**Issue by gaopinghai** [jleuschn/lodopab_tech_ref#1]
Sorry for bother, sir. I know it may be a simple question, but I do not know why the image size is set to be 26cm x 26cm. I find nothing related to it when reading "The LoDoPaB-CT Dataset" paper. Please help me, thanks!

**Comment by jleuschn** [comment]
Hi,
this is just an approximate value that in fact varies a bit, but it was the simplest to choose the same for all images. In our simulation it only influences the scaling of the projection values (via the ODL RayTransform, which considers the extent of the domain).

Looking at the original DICOM images from the LIDC-IDRI dataset in a DICOM viewer, or looking at the [ReconstructionDiameter](https://dicom.innolitics.com/ciods/ct-image/ct-image/00181100) field, one can get the diameter of the reconstructed circle.
E.g. for LIDC-IDRI-0001, -0002 and -0003, ReconstructionDiameter is 360mm, 349mm, and 420mm.
The LoDoPaB-CT images are cropped to the rectangle inside the circle, so the side lengths are `diameter/sqrt(2)`, which is around 26cm.

Don't hesitate to ask if something remains unclear.
